name: lintervention
description: Effective lint rules used internally by whynotmake.it. Based on very_good_analysis.
version: 0.1.1
repository: https://github.com/whynotmake-it/lintervention
homepage: https://whynotmake.it
topics: [lints, analyzer, analysis]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  very_good_analysis: ^5.1.0

dev_dependencies:
  melos: ^3.1.1